#VoxelCraft options
#Sat Oct 03 21:05:29 MSK 2026
handArmY=0.0
handItemRotY=0.0
handArmZ=0.0
key.BACK=83
seed=
key.JUMP=32
handItemRotX=0.0
handArmX=0.0
language=ru_ru
key.RIGHT=68
key.DROP=81
clouds=false
fov=80.0
handArmRotZ=0.0
handArmRotX=0.0
soundVolume=1.0
invertY=false
resourcePack=
handItemZ=0.0
bloomEnabled=false
fancyGraphics=false
handItemX=0.0
key.FORWARD=87
handItemY=0.0
key.SNEAK=340
viewBobbing=true
particleLevel=2
graphicsPreset=0
key.INVENTORY=69
mouseSensitivity=0.23575
vsync=true
key.SPRINT=341
handItemScale=0.05
key.LEFT=65
guiScale=2
ambientOcclusion=false
difficulty=2
dayLengthMinutes=20.0
tutorialSeen=true
renderDistance=3
fullscreen=true
menuTheme=2
autoSaveSeconds=30.0
shadows=false
fxaaEnabled=false
musicVolume=1.0
gamma=0.42142856
