#VoxelCraft options
#Fri Aug 14 03:23:04 MSK 2026
handArmY=-0.72
handItemRotY=-25.0
handArmZ=-1.2
key.BACK=83
seed=
key.JUMP=32
handItemRotX=30.0
handArmX=0.72
language=ru_ru
key.RIGHT=68
key.DROP=81
clouds=true
fov=70.0
handArmRotZ=-35.0
handArmRotX=15.0
soundVolume=1.0
resourcePack=
handItemZ=-1.45
fancyGraphics=true
handItemX=0.58
key.FORWARD=87
handItemY=-0.48
key.SNEAK=340
viewBobbing=true
particleLevel=0
key.INVENTORY=69
mouseSensitivity=0.1
vsync=true
key.SPRINT=341
handItemScale=0.4
key.LEFT=65
guiScale=0
ambientOcclusion=true
difficulty=2
renderDistance=4
fullscreen=false
shadows=true
musicVolume=1.0
gamma=0.5
